### ISSUE TITLE
Always use HtppResponseRedirect?

### ISSUE THREAD

**Issue by jrwiegand** [leifos/tango_with_django#16]
"Always return an HttpResponseRedirect after successfully dealing with POST data. This prevents data from being posted twice if a user hits the Back button."

This is included in the official Django polls tutorial. 

https://docs.djangoproject.com/en/dev/intro/tutorial04/

**Comment by drjsoundsgood** [comment]
I noticed this bug too.

I looked at your code but you haven't updated it. This is what I changed mine to:

def add_page(request, category_name_slug):

    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
                cat = None

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()
                # probably better to use a redirect here.
                return category(request, category_name_slug)
        else:
            print form.errors
    else:
        form = PageForm()

    context_dict = {'form':form, 'category': cat}

    return HttpResponseRedirect(reverse(request, 'dicer/add_page.html', context_dict))

And at the top of my views, I have imported:

from django.urls import reverse

For some reason, reverse isn't being read. It [pycharm] says that I have an unresolved reference. Any ideas?
