### ISSUE TITLE
Two errors of tango_with_django_project

### ISSUE THREAD

**Issue by Angela111** [leifos/tango_with_django#23]
There are two errors that I find when running tango_with_django_project. Firstly, in forms.py, we should add "fields=('name',)" under the class Meta in class CategoryForm(forms.ModelForm); Secondly, we should annotate the third line of bing_search.py.

**Comment by Copser** [comment]
@Angela111, I think you are in the wrong tango_whit_django project, this is the old version running whit Django 1.5.
Change the repository to tango_whit_django1.7 repository. 
In the new version they have updated forms.py whit the code you have mentioned.

**Comment by Angela111** [comment]
I got it! Thank you!

**Comment by Copser** [comment]
Just close this issue,  no problem ;-)
